k256: precompute w-NAF table sizes for window sizes (#1820)
I couldn't even get the most trivial table size calculation using
`Shleft` to work even in the playground:

https://play.rust-lang.org/?version=stable&mode=debug&edition=2024&gist=6451f352e1dbeee31b7dccaf0178ce01

Unlike bounds with e.g. `Add` that seem to work fine, `Shleft` does
something seemly ambiguous that leads to the type system recursing
infinitely:

    error[E0275]: overflow evaluating the requirement UInt<UInt<UInt<UInt<UInt<UInt<UInt<..., ...>, ...>, ...>, ...>, ...>, ...>, ...>: elliptic_curve::hybrid_array::typenum::Unsigned

Since I can't figure out another option (besides possibly mcga in the
future), this adds a `WindowSize` trait and a macro to impl it, which
has precomputed sizes for `U1`-`U8`.

This eliminates one type parameter from `WnafBase`, which is nice.
AFAICT we can't do something similar for `WnafScalar`'s `WnafStorage`
though, since it can have varying sizes.