workspace: avoid duplicates when pulling dependency from git (#1228)
When pulling dependencies using a `patch.crates-io` to a git dependency
(for unreleased crates or ...):
```
[dependencies]
p224 = "0.14.0-pre"
p256 = "0.14.0-pre.4"

[patch.crates-io]
p224 = { git = "https://github.com/RustCrypto/elliptic-curves.git" }
```

Cargo will duplicate the `primefield` and `primeorder` dependencies:
```
[[package]]
name = "p224"
version = "0.14.0-pre"
source = "git+https://github.com/RustCrypto/elliptic-curves.git#d0d84f5bcc0ed933d472548e3085f17fdea57f17"
dependencies = [
 "ecdsa",
 "elliptic-curve",
 "primefield 0.14.0-pre.2 (git+https://github.com/RustCrypto/elliptic-curves.git)",
 "primeorder 0.14.0-pre.3 (git+https://github.com/RustCrypto/elliptic-curves.git)",
 "sha2",
]

[[package]]
name = "p256"
version = "0.14.0-pre.4"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "635e1f1e5af6fc13e6c6a587fa1455e17fa7c8b54ba74093be5254819e34713f"
dependencies = [
 "ecdsa",
 "elliptic-curve",
 "primefield 0.14.0-pre.2 (registry+https://github.com/rust-lang/crates.io-index)",
 "primeorder 0.14.0-pre.3 (registry+https://github.com/rust-lang/crates.io-index)",
 "sha2",
]

[[package]]
name = "primefield"
version = "0.14.0-pre.2"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "1bbeb92947a0d0d4b0cab5e2e6749acc44c81461eb3b1aff4dbb7acd0eb9f0ab"
dependencies = [
 "crypto-bigint",
 "ff",
 "rand_core",
 "subtle",
 "zeroize",
]

[[package]]
name = "primefield"
version = "0.14.0-pre.2"
source = "git+https://github.com/RustCrypto/elliptic-curves.git#d0d84f5bcc0ed933d472548e3085f17fdea57f17"
dependencies = [
 "crypto-bigint",
 "ff",
 "rand_core",
 "subtle",
 "zeroize",
]
```

This causes issues down the line, like for nix builds and this also
makes clippy error out:
```
error: multiple versions for dependency `primefield`: 0.14.0-pre.2, 0.14.0-pre.2
  |
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#multiple_crate_versions
  = note: `-D clippy::multiple-crate-versions` implied by `-D clippy::cargo`
  = help: to override `-D clippy::cargo` add `#[allow(clippy::multiple_crate_versions)]`
```